### ISSUE TITLE
rename repo to ibm.zos_ims

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/ibm_zos_ims#1]
##### SUMMARY

Hi, can we please rename the repo to be consistent with others under gh/anisble-collections?

**Comment by itsBryantP** [comment]
We are aligning with the naming convention for several other collections under the Red Hat Ansible Certified Content for IBM Z offering. Such as ibm_zos_core and ibm_zos_zosmf. 

https://github.com/ansible-collections/ibm_zos_core
https://github.com/IBM/ibm_zos_zosmf
