### ISSUE TITLE
ims_command still requires argument "Plex"

### ISSUE THREAD

**Issue by connor-sunlife** [ansible-collections/ibm_zos_ims#106]
##### SUMMARY
The ims_command should not require any of the three parameters but when running the command it complains "Missing required arguments: plex".
I'm not sure if it is related but I do get a warning for zos_core:
[WARNING]: Collection ibm.ibm_zos_core does not support Ansible version 2.14.3

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ibm.ibm_zos_ims.ims_command

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/share/ansible/collections/ansible_collections
Collection      Version
--------------- -------
ibm.ibm_zos_ims 1.2.0
```

##### CONFIGURATION

The file is attached.
```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

Ansible Details:
Using Ansible Automation Platform
Running with an execution environment on Ansible Automation Controller
Output of gather facts is attached.
z/OS Details from gather facts:
    "ansible_distribution": "OS/390",
    "ansible_distribution_release": "27.00",
    "ansible_distribution_version": "04",
    "ansible_os_family": "OS/390",

##### STEPS TO REPRODUCE

Try to run any IMS command with the ims_command module without specifying a plex argument.

```yaml
---
- hosts: all
  gather_facts: no

  tasks:
      - name: IMS Health Check
        ibm.ibm_zos_ims.ims_command:
          command: DIS Q TRAN
          route: TST6
```

##### EXPECTED RESULTS

I expect to be returned the output from the IMS command, in this case any queued transactions.

##### ACTUAL RESULTS

An error saying that I must specify the plex argument.

```paste below
{
  "changed": false,
  "ims_output": [
    {
      "msg": "Missing required arguments: plex"
    }
  ],
  "msg": "",
  "invocation": {
    "module_args": {
      "command": "DIS Q TRAN",
      "route": [
        "TST6"
      ],
      "plex": null,
      "batch": null
    }
  },
  "_ansible_no_log": null
}
```
[ansible.txt](https://github.com/ansible-collections/ibm_zos_ims/files/11455521/ansible.txt)
[gather_facts.txt](https://github.com/ansible-collections/ibm_zos_ims/files/11455522/gather_facts.txt)

**Comment by ddgandhi** [comment]
Updated the release_notes for 1.3 release since this is known issue.
ims_command module mandates plex parameter to be required currently. 
We will revisit this module during our next release. 
Closing for now.
