### ISSUE TITLE
IMS_COMMAND - STEPLIB parameter

### ISSUE THREAD

**Issue by vcorfmatibm** [ansible-collections/ibm_zos_ims#112]
##### SUMMARY
Is there a reason that STEPLIB is not a parameter for the ims_command module? 
Moreover, if it's normal, the module's doc should mention that the STEPLIB must be specfied in the target inventory's environment variables.. because this parameter is mandatory

For the other ims modules requiring STEPLIB, there is an optional STEPLIB parameter. The STEPLIB parameter can also be specified in the target inventory's environment variables.
And in the Notes paragraph, we can read :
"The steplib parameter can also be specified in the target inventory's environment variables.
The module's steplib input parameter will take precedence over the value specified in Environment_vars."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
IMS_COMMAND

##### ANSIBLE VERSION

```ansible [core 2.11.12]
  config file = /home/vcorfmat/ansible.cfg
  configured module search path = ['/home/vcorfmat/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vcorfmat/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/vcorfmat/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/vcorfmat/.local/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
community.general 7.0.1
ibm.ibm_zos_core        1.6.0
ibm.ibm_zos_ims         1.2.0

```

**Comment by ddgandhi** [comment]
Updated the release_notes for 1.3 release since this is known issue.
We will revisit this during our next release. 
Closing for now
