### ISSUE TITLE
The doc site link in README needs to be updated

### ISSUE THREAD

**Issue by jennyhuang17** [ansible-collections/ibm_zos_ims#90]
##### SUMMARY
The link to the documentation site in [README](https://github.com/ansible-collections/ibm_zos_ims/blob/dev/README.md) directs users to the deprecated IMS Collection site. It needs to be updated to reflect the [unified doc site](https://ibm.github.io/z_ansible_collections_doc/index.html).

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
README.md

##### ANSIBLE VERSION
N/A

**Comment by jashnani** [comment]
Fixed in #116.
